"""
Scenario service.

Each scenario belongs to a project and owns its own runtime context
(ScenarioContext) + its own weather CSV on disk. No PyHelios state is
serialized anywhere — the context lives in RAM only, same lifetime as a
ProjectContext, and gets rebuilt from the weather CSV on first access
after a server restart.

Disk layout per scenario:
    data/<project_id>/<scenario_id>/weather.csv
"""
from __future__ import annotations

import shutil
from pathlib import Path

from fastapi import HTTPException
from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.scenario_context import ScenarioContext
from app.core.session_store import registry
from app.db.models import Project, Scenario
from app.helios import context as helios_ctx
from app.helios.persistence import trigger_autosave, load_scenario_snapshot


# ─── Helpers ─────────────────────────────────────────────────────────────────


def _scenario_dir(project_id: str, scenario_id: str) -> Path:
    """On-disk folder for a scenario's data."""
    return settings.data_dir / project_id / scenario_id


def _assert_project_owned(
    db: Session, session_id: str, project_id: str
) -> Project:
    """Look up the project and verify this session owns it."""
    project = (
        db.query(Project)
        .filter(Project.id == project_id, Project.session_id == session_id)
        .first()
    )
    if project is None:
        raise HTTPException(404, f"Project {project_id} not found")
    return project


def _resolve_scenario(
    session_id: str, project_id: str, scenario_id: str, db: Session
) -> ScenarioContext:
    """Auth + lazy hydration for any endpoint scoped to a scenario.

    1. Validate IDs are non-empty.
    2. Confirm the project exists in the DB and belongs to this session (→ 404).
    3. Confirm the scenario exists in the DB and belongs to the project (→ 404).
    4. Get-or-create the in-memory ScenarioContext (fresh after restart).
    5. If PyHelios is available and the scenario has no live Context yet,
       create an empty one — no file hydration (weather is session-only).
    """
    pid = project_id.strip()
    sid = scenario_id.strip()
    if not pid:
        raise HTTPException(400, "project_id is required")
    if not sid:
        raise HTTPException(400, "scenario_id is required")

    _assert_project_owned(db, session_id, pid)

    scenario = (
        db.query(Scenario)
        .filter(Scenario.id == sid, Scenario.project_id == pid)
        .first()
    )
    if scenario is None:
        raise HTTPException(404, f"Scenario {sid} not found in this project")

    sctx = registry.get_or_create_scenario_context(session_id, pid, sid)
    if helios_ctx.PYHELIOS_AVAILABLE and sctx.context is None:
        sctx.context = helios_ctx.Context()
        # Restore weather data from scenario-specific XML if it exists
        load_scenario_snapshot(sctx)
    return sctx


# ─── Endpoint handlers ───────────────────────────────────────────────────────


def create_scenario(
    session_id: str,
    project_id: str,
    name: str,
    source_scenario_id: str | None,
    db: Session,
) -> dict:
    """Create a new scenario.

    - Validates project ownership.
    - Rejects duplicate names within the project.
    - If source_scenario_id is given, copies its weather CSV to the new
      scenario's folder (byte-for-byte). Otherwise the new scenario starts
      with no weather file.
    - Registers an empty ScenarioContext in memory so the first weather
      call on the new scenario is instant.
    """
    _assert_project_owned(db, session_id, project_id)

    # Reject duplicate names (handled at DB level too, but fail fast)
    existing = (
        db.query(Scenario)
        .filter(Scenario.project_id == project_id, Scenario.name == name)
        .first()
    )
    if existing:
        raise HTTPException(400, f"Scenario '{name}' already exists in this project")

    # Resolve the source (if given)
    source: Scenario | None = None
    if source_scenario_id:
        source = (
            db.query(Scenario)
            .filter(
                Scenario.id == source_scenario_id,
                Scenario.project_id == project_id,
            )
            .first()
        )
        if source is None:
            raise HTTPException(
                404,
                f"Source scenario {source_scenario_id} not found in this project",
            )

    # Insert the new row (UUID auto-generated by model default)
    scenario = Scenario(project_id=project_id, name=name)
    try:
        db.add(scenario)
        db.commit()
        db.refresh(scenario)
    except Exception:
        db.rollback()
        raise HTTPException(500, "Failed to create scenario")

    new_dir = _scenario_dir(project_id, scenario.id)
    new_dir.mkdir(parents=True, exist_ok=True)

    # Fork weather CSV from the source, if any
    if source and source.weather_file_path:
        src_path = Path(source.weather_file_path)
        if src_path.exists():
            dst_path = new_dir / "weather.csv"
            shutil.copyfile(src_path, dst_path)
            scenario.weather_file_path = str(dst_path)
            try:
                db.commit()
                db.refresh(scenario)
            except Exception:
                db.rollback()
                raise HTTPException(500, "Failed to persist scenario weather path")

    # Register an empty ScenarioContext in memory
    registry.get_or_create_scenario_context(session_id, project_id, scenario.id)

    return {
        "success": True,
        "scenario_id": scenario.id,
        "name": scenario.name,
    }


def list_scenarios(session_id: str, project_id: str, db: Session) -> dict:
    """List all scenarios for a project."""
    _assert_project_owned(db, session_id, project_id)

    rows = (
        db.query(Scenario)
        .filter(Scenario.project_id == project_id)
        .order_by(Scenario.created_at.asc())
        .all()
    )

    return {
        "scenarios": [
            {
                "id": r.id,
                "name": r.name,
                "has_weather": bool(r.weather_file_path),
                "created_at": r.created_at,
                "updated_at": r.updated_at,
            }
            for r in rows
        ]
    }


def delete_scenario(
    session_id: str, project_id: str, scenario_id: str, db: Session
) -> dict:
    """Delete a scenario: DB row, in-memory context, and on-disk folder."""
    _assert_project_owned(db, session_id, project_id)

    scenario = (
        db.query(Scenario)
        .filter(Scenario.id == scenario_id, Scenario.project_id == project_id)
        .first()
    )
    if scenario is None:
        raise HTTPException(404, f"Scenario {scenario_id} not found")

    try:
        db.delete(scenario)
        db.commit()
    except Exception:
        db.rollback()
        raise HTTPException(500, "Failed to delete scenario")

    registry.remove_scenario(session_id, project_id, scenario_id)
    shutil.rmtree(_scenario_dir(project_id, scenario_id), ignore_errors=True)

    return {"success": True, "scenario_id": scenario_id}
