"""
Scenario service.

Each scenario belongs to a project and owns its own runtime context
(ScenarioContext) + its own weather CSV on disk. No PyHelios state is
serialized anywhere — the context lives in RAM only, same lifetime as a
ProjectContext, and gets rebuilt from the weather CSV on first access
after a server restart.

Disk layout per scenario:
    data/<project_id>/<scenario_id>/weather.csv
"""
from __future__ import annotations

import shutil
from pathlib import Path

from fastapi import HTTPException
from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.scenario_context import ScenarioContext
from app.core.session_store import registry
from app.db.models import Project, Scenario, ScenarioObject
from app.helios import context as helios_ctx
from app.helios.persistence import (
    _ensure_scenario_structure,
    load_scenario_snapshot,
)


# ─── Helpers ─────────────────────────────────────────────────────────────────


def _scenario_dir(project_id: str, scenario_id: str) -> Path:
    """Per-scenario folder, nested under its parent project."""
    return settings.scenario_dir(project_id, scenario_id)


def _assert_project_owned(
    db: Session, session_id: str, project_id: str
) -> Project:
    """Look up the project and verify this session owns it."""
    project = (
        db.query(Project)
        .filter(Project.id == project_id, Project.session_id == session_id)
        .first()
    )
    if project is None:
        raise HTTPException(404, f"Project {project_id} not found")
    return project


def _resolve_scenario(
    session_id: str, project_id: str, scenario_id: str, db: Session
) -> ScenarioContext:
    """Auth + lazy hydration for any endpoint scoped to a scenario.

    1. Validate IDs are non-empty.
    2. Confirm the project exists in the DB and belongs to this session (→ 404).
    3. Confirm the scenario exists in the DB and belongs to the project (→ 404).
    4. Get-or-create the in-memory ScenarioContext (fresh after restart).
    5. If PyHelios is available and the scenario has no live Context yet,
       create an empty one — no file hydration (weather is session-only).
    """
    pid = project_id.strip()
    sid = scenario_id.strip()
    if not pid:
        raise HTTPException(400, "project_id is required")
    if not sid:
        raise HTTPException(400, "scenario_id is required")

    _assert_project_owned(db, session_id, pid)

    scenario = (
        db.query(Scenario)
        .filter(Scenario.id == sid, Scenario.project_id == pid)
        .first()
    )
    if scenario is None:
        raise HTTPException(404, f"Scenario {sid} not found in this project")

    with registry._scenario_lock.write():
        sctx = registry.get_or_create_scenario_context(session_id, pid, sid)
        if helios_ctx.PYHELIOS_AVAILABLE and sctx.context is None:
            sctx.context = helios_ctx.Context()
            # Restore weather data from scenario-specific XML if it exists
            load_scenario_snapshot(sctx)
            # Only now is the context worth reading — `_sctx` lets callers skip
            # the lock on this flag, so it must not be set before loadXML ends.
            sctx.initialized = True
    return sctx


# ─── Endpoint handlers ───────────────────────────────────────────────────────


def create_scenario(
    session_id: str,
    project_id: str,
    name: str,
    source_scenario_id: str | None,
    db: Session,
) -> dict:
    """Create a new scenario.

    - Validates project ownership.
    - Rejects duplicate names within the project.
    - If source_scenario_id is given, copies its weather CSV to the new
      scenario's folder (byte-for-byte). Otherwise the new scenario starts
      with no weather file.
    - Registers an empty ScenarioContext in memory so the first weather
      call on the new scenario is instant.
    """
    _assert_project_owned(db, session_id, project_id)

    # Reject duplicate names (handled at DB level too, but fail fast)
    existing = (
        db.query(Scenario)
        .filter(Scenario.project_id == project_id, Scenario.name == name)
        .first()
    )
    if existing:
        raise HTTPException(400, f"Scenario '{name}' already exists in this project")

    # Resolve the source (if given)
    source: Scenario | None = None
    if source_scenario_id:
        source = (
            db.query(Scenario)
            .filter(
                Scenario.id == source_scenario_id,
                Scenario.project_id == project_id,
            )
            .first()
        )
        if source is None:
            raise HTTPException(
                404,
                f"Source scenario {source_scenario_id} not found in this project",
            )

    # Insert the new row (UUID auto-generated by model default)
    scenario = Scenario(project_id=project_id, name=name)
    try:
        db.add(scenario)
        db.commit()
        db.refresh(scenario)
    except Exception:
        db.rollback()
        raise HTTPException(500, "Failed to create scenario")

    # Scaffold the canonical per-scenario folder shape:
    #   <new_dir>/
    #     context_file/  (+ archives/)
    #     weather/
    #     metadata/
    #     export_files/
    new_dir = _ensure_scenario_structure(project_id, scenario.id)

    # Fork weather CSV from the source, if any → land it under weather/.
    if source and source.weather_file_path:
        src_path = Path(source.weather_file_path)
        if src_path.exists():
            dst_path = new_dir / "weather" / "weather.csv"
            shutil.copyfile(src_path, dst_path)
            scenario.weather_file_path = str(dst_path)
            try:
                db.commit()
                db.refresh(scenario)
            except Exception:
                db.rollback()
                raise HTTPException(500, "Failed to persist scenario weather path")

    # Register an empty ScenarioContext in memory
    registry.get_or_create_scenario_context(session_id, project_id, scenario.id)

    return {
        "success": True,
        "scenario_id": scenario.id,
        "name": scenario.name,
    }


def list_scenarios(session_id: str, project_id: str, db: Session) -> dict:
    """List all scenarios for a project."""
    _assert_project_owned(db, session_id, project_id)

    rows = (
        db.query(Scenario)
        .filter(Scenario.project_id == project_id)
        .order_by(Scenario.created_at.asc())
        .all()
    )

    return {
        "scenarios": [
            {
                "id": r.id,
                "name": r.name,
                "has_weather": bool(r.weather_file_path),
                "created_at": r.created_at,
                "updated_at": r.updated_at,
            }
            for r in rows
        ]
    }


def delete_scenario(
    session_id: str, project_id: str, scenario_id: str, db: Session
) -> dict:
    """Delete a scenario: DB row, in-memory context, and on-disk folder."""
    _assert_project_owned(db, session_id, project_id)

    scenario = (
        db.query(Scenario)
        .filter(Scenario.id == scenario_id, Scenario.project_id == project_id)
        .first()
    )
    if scenario is None:
        raise HTTPException(404, f"Scenario {scenario_id} not found")

    try:
        db.delete(scenario)
        db.commit()
    except Exception:
        db.rollback()
        raise HTTPException(500, "Failed to delete scenario")

    registry.remove_scenario(session_id, project_id, scenario_id)
    shutil.rmtree(_scenario_dir(project_id, scenario_id), ignore_errors=True)

    return {"success": True, "scenario_id": scenario_id}


# ─── Context lifecycle (explicit init + discard) ─────────────────────────────
#
# Without these, a scenario's PyHelios context is created implicitly by whichever
# request touches it first (_resolve_scenario above, or scene_object_service.
# _sctx), which silently absorbs the whole loadXML + rebuild cost with no
# progress, and is never released until the scenario or project is deleted.


def init_scenario(session_id: str, project_id: str, scenario_id: str,
                  db: Session, emit) -> None:
    """Create + hydrate a scenario's context, reporting progress through `emit`.

    Runs the work the lazy paths would otherwise do on a random request:
    Context() + load_scenario_snapshot (via _resolve_scenario) and then
    ensure_hydrated, which re-maps loaded objects and builds any that are
    missing. Once this returns, `sctx.hydrated` is True and every other
    scenario-scoped endpoint is safe to call.

    Blocking (PyHelios is synchronous) — the router runs it off the event loop.
    `emit(dict)` is called with progress events; exceptions are reported through
    it as {"error": ...} rather than raised, so the stream always terminates.
    """
    from app.services import scene_object_service as sos   # avoid import cycle

    try:
        emit({"stage": "context", "progress": 0.1,
              "message": "Loading scenario context"})
        sctx = _resolve_scenario(session_id, project_id, scenario_id, db)

        emit({"stage": "hydrate", "progress": 0.5,
              "message": "Preparing geometry"})
        sos.ensure_hydrated(db, sctx, scenario_id)

        # Hydration only QUEUES its context.xml save. Wait for it here so
        # "ready" means the write is done too — this is the request that is
        # still reporting progress, and the client's next call is not.
        emit({"stage": "persist", "progress": 0.9,
              "message": "Saving scenario"})
        sos.wait_for_saves()

        # "Ready" means every geometry the DB says exists is LIVE in the context,
        # not merely that hydration returned. It swallows per-object build
        # failures on purpose (`except HTTPException: continue`) so one bad row
        # cannot make a scenario unopenable — but that left init reporting
        # {"objects": 0, "message": "Scenario ready"} for a scenario where
        # nothing loaded, while the object list still returned every row. The
        # client then drew a geometry that has no primitives behind it.
        expected = (
            db.query(ScenarioObject)
            .filter(ScenarioObject.scenario_id == scenario_id)
            .count()
        )
        objects = len(sctx.persisted_objects) if sctx.persisted_objects else 0
        if objects < expected:
            emit({"error": f"{expected - objects} of {expected} geometries could not "
                            f"be loaded into the scenario",
                  "objects": objects, "expected": expected})
            return

        emit({"stage": "done", "progress": 1.0, "objects": objects,
              "message": "Scenario ready"})
    except HTTPException as exc:
        emit({"error": exc.detail, "status": exc.status_code})
    except Exception as exc:   # noqa: BLE001 — the stream must always end
        emit({"error": str(exc) or exc.__class__.__name__})


def discard_scenario(session_id: str, project_id: str, scenario_id: str) -> dict:
    """Autosave a scenario's context to context.xml, then drop it from memory.

    Called when the user switches away. The registry lock is held across remove +
    save so a concurrent _sctx/_resolve_scenario cannot re-create the context
    half-way through the teardown. A scenario with no live context is a no-op
    success — discard is idempotent and safe to call blindly on navigation.

    The entry is dropped BEFORE the save, not after: _sctx returns an already-live
    scenario without taking the lock, so an entry left in place for the duration
    of the write would be handed to a request as if it were current. Removing
    first makes that lookup miss, and the request then waits on the lock exactly
    as it used to. `sctx` is a local reference, so the save is unaffected.
    """
    from app.helios.persistence import trigger_scenario_autosave

    with registry._scenario_lock.write():
        sctx = registry.get_scenario_context(session_id, project_id, scenario_id)
        if sctx is None:
            return {"success": True, "scenario_id": scenario_id, "discarded": False}
        registry.remove_scenario(session_id, project_id, scenario_id)
        saved = False
        try:
            trigger_scenario_autosave(sctx)
            saved = True
        except Exception:
            pass    # never block the release on a save failure
    return {"success": True, "scenario_id": scenario_id,
            "discarded": True, "saved": saved}
